using System;
using System.Diagnostics.CodeAnalysis;
using System.Linq;

namespace ISCM.BugFinder.Core.Contracts;

/// <summary>
/// H-01.2: Canonical Identifier Contract.
/// Ten typed identities replacing naked string joins (audit X-005).
/// Rules:
///   - Value equality (records): same value == same identity.
///   - Validation in factories; TryParse for external/untrusted input.
///   - NO generation inside Core (no Guid.NewGuid / DateTime.Now) -
///     callers inject raw values (determinism, audit X-003 / H-13.3).
///   - Formats:
///       FailureSignature   FS-&lt;64 hex&gt;   content-derived (generated in H-02)
///       FailureId          F-&lt;64 hex&gt;    logical failure, signature-derived
///       FailureInstanceId  FI|&lt;FailureId&gt;|&lt;ExecutionSessionId&gt;
///       EvidenceId         EV-&lt;32 hex&gt;   provider-injected (hash in H-08.9)
///       ExecutionSessionId ES-&lt;32 hex&gt;
///       InvestigationId    INV-&lt;32 hex&gt;
///       RevisionId         git SHA (7..64 hex)
///       SymbolKey          &lt;K&gt;|&lt;Assembly&gt;|&lt;FQN&gt;&lt;(params)&gt;  (BF-13.4 StableKey)
///       TargetKey          SymbolKey | FILE|&lt;path&gt;           (BF-14.1 grouping key)
///       LocationId         LOC|&lt;path&gt;|L&lt;line?&gt;
///   JSON converters for these types land with H-01.3 (schema versioning).
/// </summary>
public enum TargetKeyKind { Symbol, File, Other }

internal static class IdentifierValidation
{
    public static string NonEmpty(string value, string paramName)
    {
        if (string.IsNullOrWhiteSpace(value))
            throw new ArgumentException("Identifier value is required.", paramName);
        return value.Trim();
    }

    public static bool IsHex(string text) =>
        text.Length > 0 && text.All(c =>
            c is >= '0' and <= '9' or >= 'a' and <= 'f' or >= 'A' and <= 'F');

    public static bool MatchesPrefixedHex(string? value, string prefix, int hexLength)
    {
        if (value is null) return false;
        var v = value.Trim();
        return v.Length == prefix.Length + 1 + hexLength
            && v.StartsWith(prefix + "-", StringComparison.Ordinal)
            && IsHex(v[(prefix.Length + 1)..]);
    }
}

/// <summary>Shared base for prefixed-hex identifiers (FS/F/EV/ES/INV family).</summary>
public abstract record PrefixedHexIdentifier
{
    public string Value { get; }
    protected PrefixedHexIdentifier(string value) => Value = value;

    protected static string Validate(string value, string prefix, int hexLength, string paramName)
    {
        var v = IdentifierValidation.NonEmpty(value, paramName);
        if (!IdentifierValidation.MatchesPrefixedHex(v, prefix, hexLength))
            throw new ArgumentException(
                $"{prefix} identifier must match '{prefix}-<{hexLength} hex chars>': '{value}'.", paramName);
        return v;
    }

    protected static bool Matches(string? value, string prefix, int hexLength) =>
        IdentifierValidation.MatchesPrefixedHex(value, prefix, hexLength);
}

/// <summary>H-01.2.3: content-derived failure signature (generated by H-02.2).</summary>
public sealed record FailureSignature : PrefixedHexIdentifier
{
    public const string Prefix = "FS";
    public const int HexLength = 64;
    private FailureSignature(string value) : base(value) { }

    public static FailureSignature Create(string value) =>
        TryParse(value, out var parsed)
            ? parsed
            : throw new ArgumentException($"Invalid {Prefix} identifier: '{value}'.", nameof(value));

    public static bool TryParse([NotNullWhen(true)] string? value,
        [NotNullWhen(true)] out FailureSignature? parsed)
    {
        if (value is not null && Matches(value, Prefix, HexLength))
        {
            parsed = new FailureSignature(value.Trim());
            return true;
        }
        parsed = null;
        return false;
    }

    public sealed override string ToString() => Value;
}

/// <summary>H-01.2.1: stable logical failure id (signature-derived in H-02).</summary>
public sealed record FailureId : PrefixedHexIdentifier
{
    public const string Prefix = "F";
    public const int HexLength = 64;
    private FailureId(string value) : base(value) { }

    public static FailureId Create(string value) =>
        TryParse(value, out var parsed)
            ? parsed
            : throw new ArgumentException($"Invalid {Prefix} identifier: '{value}'.", nameof(value));

    public static bool TryParse([NotNullWhen(true)] string? value,
        [NotNullWhen(true)] out FailureId? parsed)
    {
        if (value is not null && Matches(value, Prefix, HexLength))
        {
            parsed = new FailureId(value.Trim());
            return true;
        }
        parsed = null;
        return false;
    }

    public sealed override string ToString() => Value;
}

/// <summary>H-01.2.4: one immutable evidence item id (hash model lands in H-08.9).</summary>
public sealed record EvidenceId : PrefixedHexIdentifier
{
    public const string Prefix = "EV";
    public const int HexLength = 32;
    private EvidenceId(string value) : base(value) { }

    public static EvidenceId Create(string value) =>
        TryParse(value, out var parsed)
            ? parsed
            : throw new ArgumentException($"Invalid {Prefix} identifier: '{value}'.", nameof(value));

    public static bool TryParse([NotNullWhen(true)] string? value,
        [NotNullWhen(true)] out EvidenceId? parsed)
    {
        if (value is not null && Matches(value, Prefix, HexLength))
        {
            parsed = new EvidenceId(value.Trim());
            return true;
        }
        parsed = null;
        return false;
    }

    public sealed override string ToString() => Value;
}

/// <summary>H-01.2.8: one test-execution session id.</summary>
public sealed record ExecutionSessionId : PrefixedHexIdentifier
{
    public const string Prefix = "ES";
    public const int HexLength = 32;
    private ExecutionSessionId(string value) : base(value) { }

    public static ExecutionSessionId Create(string value) =>
        TryParse(value, out var parsed)
            ? parsed
            : throw new ArgumentException($"Invalid {Prefix} identifier: '{value}'.", nameof(value));

    public static bool TryParse([NotNullWhen(true)] string? value,
        [NotNullWhen(true)] out ExecutionSessionId? parsed)
    {
        if (value is not null && Matches(value, Prefix, HexLength))
        {
            parsed = new ExecutionSessionId(value.Trim());
            return true;
        }
        parsed = null;
        return false;
    }

    public sealed override string ToString() => Value;
}

/// <summary>H-01.2.9: one investigation run id.</summary>
public sealed record InvestigationId : PrefixedHexIdentifier
{
    public const string Prefix = "INV";
    public const int HexLength = 32;
    private InvestigationId(string value) : base(value) { }

    public static InvestigationId Create(string value) =>
        TryParse(value, out var parsed)
            ? parsed
            : throw new ArgumentException($"Invalid {Prefix} identifier: '{value}'.", nameof(value));

    public static bool TryParse([NotNullWhen(true)] string? value,
        [NotNullWhen(true)] out InvestigationId? parsed)
    {
        if (value is not null && Matches(value, Prefix, HexLength))
        {
            parsed = new InvestigationId(value.Trim());
            return true;
        }
        parsed = null;
        return false;
    }

    public sealed override string ToString() => Value;
}

/// <summary>H-01.2.2: one concrete occurrence of a failure (signature + session).</summary>
public sealed record FailureInstanceId
{
    public string Value { get; }
    public FailureId Failure { get; }
    public ExecutionSessionId Session { get; }

    private FailureInstanceId(string value, FailureId failure, ExecutionSessionId session)
        => (Value, Failure, Session) = (value, failure, session);

    public static FailureInstanceId Create(FailureId failure, ExecutionSessionId session)
    {
        if (failure is null) throw new ArgumentNullException(nameof(failure));
        if (session is null) throw new ArgumentNullException(nameof(session));
        return new FailureInstanceId($"FI|{failure.Value}|{session.Value}", failure, session);
    }

    public static bool TryParse([NotNullWhen(true)] string? value,
        [NotNullWhen(true)] out FailureInstanceId? parsed)
    {
        parsed = null;
        if (string.IsNullOrWhiteSpace(value)) return false;
        var segments = value.Trim().Split('|');
        if (segments.Length != 3 || segments[0] != "FI") return false;
        if (!FailureId.TryParse(segments[1], out var failure)) return false;
        if (!ExecutionSessionId.TryParse(segments[2], out var session)) return false;
        parsed = new FailureInstanceId(value.Trim(), failure, session);
        return true;
    }

    public override string ToString() => Value;
}

/// <summary>H-01.2.10: a git revision (full or short SHA).</summary>
public sealed record RevisionId
{
    public string Value { get; }
    private RevisionId(string value) => Value = value;

    public static RevisionId Create(string value) =>
        TryParse(value, out var parsed)
            ? parsed
            : throw new ArgumentException(
                $"RevisionId must be a git SHA (7..64 hex chars): '{value}'.", nameof(value));

    public static bool TryParse([NotNullWhen(true)] string? value,
        [NotNullWhen(true)] out RevisionId? parsed)
    {
        parsed = null;
        if (string.IsNullOrWhiteSpace(value)) return false;
        var v = value.Trim();
        if (v.Length < 7 || v.Length > 64 || !IdentifierValidation.IsHex(v)) return false;
        parsed = new RevisionId(v);
        return true;
    }

    public override string ToString() => Value;
}

/// <summary>H-01.2.6: canonical symbol identity (BF-13.4 StableKey format).</summary>
public sealed record SymbolKey
{
    public const string KindCodes = "TMPFS";
    public string Value { get; }
    private SymbolKey(string value) => Value = value;

    public static SymbolKey FromStableKey(string value) =>
        TryParse(value, out var parsed)
            ? parsed
            : throw new ArgumentException(
                "Invalid SymbolKey (expected kind|assembly|fqn with kind in {T,M,P,F,S}): " +
                $"'{value}'.", nameof(value));

    public static bool TryParse([NotNullWhen(true)] string? value,
        [NotNullWhen(true)] out SymbolKey? parsed)
    {
        parsed = null;
        if (string.IsNullOrWhiteSpace(value)) return false;
        var v = value.Trim();
        var segments = v.Split('|');
        if (segments.Length < 3) return false;
        if (segments[0].Length != 1 || !KindCodes.Contains(segments[0][0])) return false;
        parsed = new SymbolKey(v);
        return true;
    }

    public override string ToString() => Value;
}

/// <summary>H-01.2.5: fusion grouping key (symbol or file - BF-14.1 contract).</summary>
public sealed record TargetKey
{
    public string Value { get; }
    public TargetKeyKind Kind { get; }
    private TargetKey(string value, TargetKeyKind kind) => (Value, Kind) = (value, kind);

    public static TargetKey FromSymbol(SymbolKey symbol)
    {
        if (symbol is null) throw new ArgumentNullException(nameof(symbol));
        return new TargetKey(symbol.Value, TargetKeyKind.Symbol);
    }

    public static TargetKey FromFile(string filePath)
    {
        var v = IdentifierValidation.NonEmpty(filePath, nameof(filePath)).Replace('\\', '/');
        return new TargetKey($"FILE|{v}", TargetKeyKind.File);
    }

    /// <summary>Legacy adoption path (H-01.7): wraps existing string keys as-is.</summary>
    public static TargetKey FromRaw(string raw)
    {
        var v = IdentifierValidation.NonEmpty(raw, nameof(raw));
        return new TargetKey(v, Classify(v));
    }

    private static TargetKeyKind Classify(string v)
    {
        if (v.StartsWith("FILE|", StringComparison.Ordinal)) return TargetKeyKind.File;
        var first = v.Split('|')[0];
        if (first.Length == 1 && SymbolKey.KindCodes.Contains(first[0])) return TargetKeyKind.Symbol;
        return TargetKeyKind.Other;
    }

    public override string ToString() => Value;
}

/// <summary>H-01.2.7: source location identity (file + optional line).</summary>
public sealed record LocationId
{
    public string Value { get; }
    private LocationId(string value) => Value = value;

    public static LocationId Create(string filePath, int? lineNumber = null)
    {
        var v = IdentifierValidation.NonEmpty(filePath, nameof(filePath)).Replace('\\', '/');
        return lineNumber is null
            ? new LocationId($"LOC|{v}")
            : new LocationId($"LOC|{v}|L{lineNumber.Value}");
    }

    public static bool TryParse([NotNullWhen(true)] string? value,
        [NotNullWhen(true)] out LocationId? parsed)
    {
        parsed = null;
        if (string.IsNullOrWhiteSpace(value)) return false;
        var v = value.Trim();
        if (!v.StartsWith("LOC|", StringComparison.Ordinal)) return false;
        var segments = v.Split('|');
        if (segments.Length < 2 || segments.Length > 3) return false;
        if (segments.Length == 3 && (segments[2].Length < 2 || segments[2][0] != 'L'
            || !int.TryParse(segments[2].AsSpan(1), out _))) return false;
        parsed = new LocationId(v);
        return true;
    }

    public override string ToString() => Value;
}