namespace ISCM.Domain.Entities;

// Step 28 fix: all paths verified 1:1 against the Revised PDF.
// Covers PDF items 10 (Firewall), 14 (Windows Update), 15 (Autorun), 16 (RDP).
public static partial class GuidanceCatalog
{
    // ── Item 10: Windows Defender Firewall ──
    private static readonly bool _fw = Register(
        new SubCheck
        {
            Id = "FW-001.1",
            Title = "Domain Profile — state / inbound / outbound",
            Expected = "On / Block / Allow",
            WhatItDoes = "Enables firewall and blocks unsolicited inbound on domain networks.",
            Recommendation = "Domain: Enabled, Inbound Block, Outbound Allow.",
            CheckCurrentCli = "Get-NetFirewallProfile -Profile Domain | Select Enabled,DefaultInboundAction,DefaultOutboundAction",
            CliCommand = "Set-NetFirewallProfile -Profile Domain -Enabled True -DefaultInboundAction Block -DefaultOutboundAction Allow",
            VerifyCli = "Get-NetFirewallProfile -Profile Domain | Select Enabled,DefaultInboundAction,DefaultOutboundAction",
            Verification = "Enabled True, Inbound Block, Outbound Allow.",
            ValueMap = "Enabled True = On; Block = inbound default.",
            CliTokens = "-Profile Domain: domain network profile; -DefaultInboundAction Block: deny unsolicited inbound.",
            ConsoleTool = "wf.msc",
            DestinationLabel = "Firewall Properties → Domain Profile",
            GraphicalPathFull = "Computer Configuration > Windows Settings > Security Settings > Windows Defender Firewall with Advanced Security > Windows Defender Firewall Properties > Domain Profile",
            ConsolePath = "Windows Defender Firewall with Advanced Security > Windows Defender Firewall Properties > Domain Profile",
            YouAreHere = "wf.msc (root)",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Windows Defender Firewall with Advanced Security > Windows Defender Firewall Properties > Domain Profile > State = On, Inbound = Block, Outbound = Allow",
            GraphicalSteps = "1) wf.msc. 2) Right-click root → Properties. 3) Domain Profile tab. 4) State=On, Inbound=Block, Outbound=Allow.",
            UndoCli = "Set-NetFirewallProfile -Profile Domain -Enabled False",
            IgnoreConsequence = "Domain network left unprotected.",
            HasRegistryPath = false
        },
        new SubCheck
        {
            Id = "FW-001.2",
            Title = "Private Profile — state / inbound",
            Expected = "On / Block",
            WhatItDoes = "Enables firewall on private networks.",
            Recommendation = "Private: Enabled, Inbound Block.",
            CheckCurrentCli = "Get-NetFirewallProfile -Profile Private | Select Enabled,DefaultInboundAction",
            CliCommand = "Set-NetFirewallProfile -Profile Private -Enabled True -DefaultInboundAction Block",
            VerifyCli = "Get-NetFirewallProfile -Profile Private | Select Enabled,DefaultInboundAction",
            Verification = "Enabled True, Inbound Block.",
            ValueMap = "Enabled True = On.",
            CliTokens = "-Profile Private: private network profile.",
            ConsoleTool = "wf.msc",
            DestinationLabel = "Firewall Properties → Private Profile",
            GraphicalPathFull = "Computer Configuration > Windows Settings > Security Settings > Windows Defender Firewall with Advanced Security > Windows Defender Firewall Properties > Private Profile",
            ConsolePath = "Windows Defender Firewall with Advanced Security > Windows Defender Firewall Properties > Private Profile",
            YouAreHere = "wf.msc (root)",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Windows Defender Firewall with Advanced Security > Windows Defender Firewall Properties > Private Profile > State = On, Inbound = Block",
            GraphicalSteps = "1) wf.msc → Properties. 2) Private Profile tab. 3) State=On, Inbound=Block.",
            UndoCli = "Set-NetFirewallProfile -Profile Private -Enabled False",
            IgnoreConsequence = "Private network left unprotected.",
            HasRegistryPath = false
        },
        new SubCheck
        {
            Id = "FW-001.3",
            Title = "Public Profile — state / inbound",
            Expected = "On / Block all",
            WhatItDoes = "Strictest posture on public networks.",
            Recommendation = "Public: Enabled, Inbound Block.",
            CheckCurrentCli = "Get-NetFirewallProfile -Profile Public | Select Enabled,DefaultInboundAction",
            CliCommand = "Set-NetFirewallProfile -Profile Public -Enabled True -DefaultInboundAction Block",
            VerifyCli = "Get-NetFirewallProfile -Profile Public | Select Enabled,DefaultInboundAction",
            Verification = "Enabled True, Inbound Block.",
            ValueMap = "Enabled True = On.",
            CliTokens = "-Profile Public: public network profile.",
            ConsoleTool = "wf.msc",
            DestinationLabel = "Firewall Properties → Public Profile",
            GraphicalPathFull = "Computer Configuration > Windows Settings > Security Settings > Windows Defender Firewall with Advanced Security > Windows Defender Firewall Properties > Public Profile",
            ConsolePath = "Windows Defender Firewall with Advanced Security > Windows Defender Firewall Properties > Public Profile",
            YouAreHere = "wf.msc (root)",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Windows Defender Firewall with Advanced Security > Windows Defender Firewall Properties > Public Profile > State = On, Inbound = Block all",
            GraphicalSteps = "1) wf.msc → Properties. 2) Public Profile tab. 3) State=On, Inbound=Block.",
            UndoCli = "Set-NetFirewallProfile -Profile Public -Enabled False",
            IgnoreConsequence = "Public network fully exposed.",
            HasRegistryPath = false
        },
        new SubCheck
        {
            Id = "FW-001.4",
            Title = "Display a notification (all profiles)",
            Expected = "No",
            WhatItDoes = "Suppresses blocked-program pop-ups.",
            Recommendation = "DisableNotifications = 1 per profile.",
            CheckCurrentCli = "Get-ChildItem 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\WindowsFirewall' | Get-ItemProperty | Select DisableNotifications",
            CliCommand = "foreach ($p in 'DomainProfile','PrivateProfile','PublicProfile') { Set-ItemProperty -Path \"HKLM:\\SOFTWARE\\Policies\\Microsoft\\WindowsFirewall\\$p\" -Name DisableNotifications -Value 1 }",
            VerifyCli = "Get-ChildItem 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\WindowsFirewall' | Get-ItemProperty | Select DisableNotifications",
            Verification = "DisableNotifications = 1 on all profiles.",
            ValueMap = "1 = No notification.",
            CliTokens = "DisableNotifications: turns off blocked-program pop-ups.",
            ConsoleTool = "wf.msc",
            DestinationLabel = "Firewall Properties → profile → Customize → Firewall settings",
            GraphicalPathFull = "Windows Defender Firewall Properties > each Profile tab > Customize (under Settings) > Firewall settings > Display a notification = No",
            ConsolePath = "Windows Defender Firewall Properties > Profile tab > Customize > Firewall settings",
            YouAreHere = "wf.msc → Properties",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Windows Defender Firewall with Advanced Security > Windows Defender Firewall Properties > [Profile] tab > Customize > Firewall settings > Display a notification > No",
            GraphicalSteps = "1) wf.msc → Properties. 2) For each profile tab: Customize under Settings. 3) Firewall settings → Display a notification = No.",
            UndoCli = "# set DisableNotifications = 0",
            IgnoreConsequence = "Cosmetic only; pop-ups remain.",
            HasRegistryPath = true,
            RegistryPath = @"HKLM\SOFTWARE\Policies\Microsoft\WindowsFirewall",
            AlternativeToRegistry = "Prefer wf.msc Properties → Customize."
        },
        new SubCheck
        {
            Id = "FW-001.5",
            Title = "Apply local firewall / connection security rules",
            Expected = "No (high-security)",
            WhatItDoes = "Ensures only centrally managed rules apply.",
            Recommendation = "AllowLocalPolicyMerge=0, AllowLocalIPsecPolicyMerge=0.",
            CheckCurrentCli = "Get-ChildItem 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\WindowsFirewall' | Get-ItemProperty | Select AllowLocalPolicyMerge,AllowLocalIPsecPolicyMerge",
            CliCommand = "foreach ($p in 'DomainProfile','PrivateProfile','PublicProfile') { Set-ItemProperty -Path \"HKLM:\\SOFTWARE\\Policies\\Microsoft\\WindowsFirewall\\$p\" -Name AllowLocalPolicyMerge -Value 0; Set-ItemProperty -Path \"HKLM:\\SOFTWARE\\Policies\\Microsoft\\WindowsFirewall\\$p\" -Name AllowLocalIPsecPolicyMerge -Value 0 }",
            VerifyCli = "Get-ChildItem 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\WindowsFirewall' | Get-ItemProperty | Select AllowLocalPolicyMerge",
            Verification = "Both merge values = 0.",
            ValueMap = "0 = No (ignore local rules).",
            CliTokens = "AllowLocalPolicyMerge: whether local rules are merged; 0 = GPO-only.",
            ConsoleTool = "wf.msc",
            DestinationLabel = "Firewall Properties → profile → Customize → Rule merging",
            GraphicalPathFull = "Windows Defender Firewall Properties > each Profile tab > Customize > Rule merging > Apply local firewall rules = No",
            ConsolePath = "Windows Defender Firewall Properties > Profile tab > Customize > Rule merging",
            YouAreHere = "wf.msc → Properties",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Windows Defender Firewall with Advanced Security > Windows Defender Firewall Properties > [Profile] tab > Customize > Rule merging > Apply local firewall rules > No",
            GraphicalSteps = "1) wf.msc → Properties. 2) Each profile tab → Customize. 3) Rule merging → Apply local firewall/connection security rules = No.",
            UndoCli = "# set merge values = 1",
            IgnoreConsequence = "Local admins can bypass central rules.",
            HasRegistryPath = true,
            RegistryPath = @"HKLM\SOFTWARE\Policies\Microsoft\WindowsFirewall",
            AlternativeToRegistry = "Prefer wf.msc Properties → Customize."
        });

    // ── Item 14: Windows Update (isolated-network aware) ──
    private static readonly bool _wup = Register(
        new SubCheck
        {
            Id = "WUP-001.1",
            Title = "Configure Automatic Updates (model-aware)",
            Expected = "WSUS-backed: Enabled=4 · Isolated w/o server: Disabled/NotConfigured",
            WhatItDoes = "Controls managed automatic update behavior.",
            Recommendation = "Pick per your patch model.",
            CheckCurrentCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' | Select NoAutoUpdate,AUOptions",
            CliCommand = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' -Name NoAutoUpdate -Value 0; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' -Name AUOptions -Value 4",
            VerifyCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' | Select AUOptions",
            Verification = "AUOptions=4 (WSUS-backed) or Disabled for fully-isolated no-server clients.",
            ValueMap = "AUOptions 4 = auto download+schedule; NoAutoUpdate 1 = disabled.",
            CliTokens = "AUOptions: update mode; 4 = auto download & schedule.",
            ConsoleTool = "gpedit.msc",
            DestinationLabel = "Windows Update → Configure Automatic Updates",
            GraphicalPathFull = "Computer Configuration > Administrative Templates > Windows Components > Windows Update > Configure Automatic Updates",
            ConsolePath = "Computer Configuration > Administrative Templates > Windows Components > Windows Update",
            YouAreHere = "gpedit.msc (root)",
            GoTo = "Computer Configuration > Administrative Templates > Windows Components > Windows Update > 'Configure Automatic Updates' > Enabled > 4 - Auto download and schedule the install",
            GraphicalSteps = "1) gpedit.msc → Windows Components → Windows Update. 2) Configure Automatic Updates. 3) Enabled=4 (WSUS) or Disabled (isolated, no server).",
            UndoCli = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' -Name NoAutoUpdate -Value 1",
            IgnoreConsequence = "Patches never install automatically.",
            HasRegistryPath = true,
            RegistryPath = @"HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU\AUOptions",
            AlternativeToRegistry = "Prefer gpedit.msc → Windows Update."
        },
        new SubCheck
        {
            Id = "WUP-001.2",
            Title = "Specify intranet Microsoft update service location (WSUS)",
            Expected = "Enabled with internal WSUS URL (only if WSUS exists)",
            WhatItDoes = "Redirects clients to an internal offline WSUS server.",
            Recommendation = "Set only when an internal WSUS is deployed.",
            CheckCurrentCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate' | Select WUServer,WUStatusServer",
            CliCommand = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate' -Name WUServer -Value 'http://wsus.internal:8530'; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate' -Name WUStatusServer -Value 'http://wsus.internal:8530'",
            VerifyCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate' | Select WUServer",
            Verification = "WUServer/WUStatusServer point to the internal WSUS.",
            ValueMap = "",
            CliTokens = "WUServer: internal update source URL.",
            ConsoleTool = "gpedit.msc",
            DestinationLabel = "Windows Update → Specify intranet update service location",
            GraphicalPathFull = "Computer Configuration > Administrative Templates > Windows Components > Windows Update > Specify intranet Microsoft update service location",
            ConsolePath = "Computer Configuration > Administrative Templates > Windows Components > Windows Update",
            YouAreHere = "gpedit.msc (root)",
            GoTo = "Computer Configuration > Administrative Templates > Windows Components > Windows Update > 'Scheduled install day' > 0 - Every day",
            GraphicalSteps = "1) Windows Update. 2) Specify intranet Microsoft update service location. 3) Enter internal WSUS URL.",
            UndoCli = "# remove WUServer/WUStatusServer",
            IgnoreConsequence = "Clients may try Internet update servers.",
            HasRegistryPath = true,
            RegistryPath = @"HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\WUServer",
            AlternativeToRegistry = "Prefer gpedit.msc → Windows Update."
        },
        new SubCheck
        {
            Id = "WUP-001.3",
            Title = "No auto-restart with logged on users",
            Expected = "Per maintenance-window policy",
            WhatItDoes = "Aligns reboots with operations instead of forcing one answer.",
            Recommendation = "Set per environment.",
            CheckCurrentCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' | Select NoAutoRebootWithLoggedOnUsers",
            CliCommand = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' -Name NoAutoRebootWithLoggedOnUsers -Value 0",
            VerifyCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' | Select NoAutoRebootWithLoggedOnUsers",
            Verification = "Value matches your maintenance policy.",
            ValueMap = "0 = allow restart; 1 = no auto-restart.",
            CliTokens = "NoAutoRebootWithLoggedOnUsers: controls forced reboot with logged-on users.",
            ConsoleTool = "gpedit.msc",
            DestinationLabel = "Windows Update → No auto-restart",
            GraphicalPathFull = "Computer Configuration > Administrative Templates > Windows Components > Windows Update > No auto-restart with logged on users for scheduled automatic updates installations",
            ConsolePath = "Computer Configuration > Administrative Templates > Windows Components > Windows Update",
            YouAreHere = "gpedit.msc (root)",
            GoTo = "Computer Configuration > Administrative Templates > Windows Components > Windows Update > 'No auto-restart with logged on users for scheduled automatic updates installations' > Disabled",
            GraphicalSteps = "1) Windows Update. 2) 'No auto-restart…' per policy.",
            UndoCli = "# invert value",
            IgnoreConsequence = "Reboots may interrupt users or stall patching.",
            HasRegistryPath = true,
            RegistryPath = @"HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU\NoAutoRebootWithLoggedOnUsers",
            AlternativeToRegistry = "Prefer gpedit.msc → Windows Update."
        },
        new SubCheck
        {
            Id = "WUP-001.4",
            Title = "Verify latest patches (build-aware)",
            Expected = "Latest monthly KB for exact build",
            WhatItDoes = "Confirms the client has the newest cumulative update for its exact 22H2/23H2/24H2/25H2/26H1 build.",
            Recommendation = "Compare Get-HotFix top entry with the release-information page.",
            CheckCurrentCli = "Get-HotFix | Sort-Object InstalledOn -Descending | Select-Object -First 15",
            CliCommand = "# compare build via winver, then install .msu: wusa.exe Windows11.0-KBxxxxxxx-x64.msu /quiet /norestart",
            VerifyCli = "Get-HotFix -Id KBxxxxxxx",
            Verification = "Target KB present for the exact build.",
            ValueMap = "",
            CliTokens = "Get-HotFix: lists installed KBs; wusa: installs an MSU.",
            ConsoleTool = "winver",
            DestinationLabel = "winver → identify build",
            GraphicalPathFull = "Settings > System > About (or winver) to identify build, then Microsoft Update Catalog for the matching KB",
            ConsolePath = "Settings > System > About",
            YouAreHere = "Desktop",
            GoTo = "Run Cli 'winver' On 'Window + R' / Settings → System → About → note OS build",
            GraphicalSteps = "1) Run winver. 2) Note version/build. 3) Match against release-information + KB article.",
            UndoCli = "# n/a",
            IgnoreConsequence = "Unknown patch gap remains.",
            HasRegistryPath = false
        });

    // ── Item 15: Autorun/Autoplay ──
    private static readonly bool _ard = Register(
        new SubCheck
        {
            Id = "ARD-001.1",
            Title = "Turn off AutoPlay",
            Expected = "Enabled — All drives",
            WhatItDoes = "Disables AutoPlay on every drive type including USB.",
            Recommendation = "NoDriveTypeAutoRun = 255.",
            CheckCurrentCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer' | Select NoDriveTypeAutoRun",
            CliCommand = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer' -Name NoDriveTypeAutoRun -Value 255 -Type DWord",
            VerifyCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer' | Select NoDriveTypeAutoRun",
            Verification = "NoDriveTypeAutoRun = 255.",
            ValueMap = "255 = all drives off.",
            CliTokens = "NoDriveTypeAutoRun 255: disables AutoPlay for all drive types.",
            ConsoleTool = "gpedit.msc",
            DestinationLabel = "AutoPlay Policies → Turn off AutoPlay",
            GraphicalPathFull = "Computer Configuration > Administrative Templates > Windows Components > AutoPlay Policies > Turn off AutoPlay",
            ConsolePath = "Computer Configuration > Administrative Templates > Windows Components > AutoPlay Policies",
            YouAreHere = "gpedit.msc (root)",
            GoTo = "Computer Configuration > Administrative Templates > Windows Components > AutoPlay Policies > 'Turn off AutoPlay' > Enabled > All drives",
            GraphicalSteps = "1) gpedit.msc → Windows Components → AutoPlay Policies. 2) Turn off AutoPlay. 3) Enabled, option All drives.",
            UndoCli = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer' -Name NoDriveTypeAutoRun -Value 0",
            IgnoreConsequence = "USB malware can auto-execute.",
            HasRegistryPath = true,
            RegistryPath = @"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\NoDriveTypeAutoRun",
            AlternativeToRegistry = "Prefer gpedit.msc → AutoPlay Policies."
        },
        new SubCheck
        {
            Id = "ARD-001.2",
            Title = "Set the default behavior for AutoRun",
            Expected = "Enabled — Do not execute any autorun commands",
            WhatItDoes = "Prevents autorun.inf auto-execution.",
            Recommendation = "NoAutorun = 1.",
            CheckCurrentCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer' | Select NoAutorun",
            CliCommand = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer' -Name NoAutorun -Value 1 -Type DWord",
            VerifyCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer' | Select NoAutorun",
            Verification = "NoAutorun = 1.",
            ValueMap = "1 = do not execute autorun.",
            CliTokens = "NoAutorun 1: blocks autorun.inf commands.",
            ConsoleTool = "gpedit.msc",
            DestinationLabel = "AutoPlay Policies → Default behavior for AutoRun",
            GraphicalPathFull = "Computer Configuration > Administrative Templates > Windows Components > AutoPlay Policies > Set the default behavior for AutoRun",
            ConsolePath = "Computer Configuration > Administrative Templates > Windows Components > AutoPlay Policies",
            YouAreHere = "gpedit.msc (root)",
            GoTo = "Computer Configuration > Administrative Templates > Windows Components > AutoPlay Policies > 'Set the default behavior for AutoRun' > Enabled > Do not execute any autorun commands",
            GraphicalSteps = "1) AutoPlay Policies. 2) 'Set the default behavior for AutoRun'. 3) Enabled — Do not execute any autorun commands.",
            UndoCli = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer' -Name NoAutorun -Value 0",
            IgnoreConsequence = "autorun.inf still runs.",
            HasRegistryPath = true,
            RegistryPath = @"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\NoAutorun",
            AlternativeToRegistry = "Prefer gpedit.msc → AutoPlay Policies."
        },
        new SubCheck
        {
            Id = "ARD-001.3",
            Title = "Disallow Autoplay for non-volume devices",
            Expected = "Enabled",
            WhatItDoes = "Blocks AutoPlay for MTP phones/cameras.",
            Recommendation = "NoAutoplayfornonVolume = 1.",
            CheckCurrentCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer' | Select NoAutoplayfornonVolume",
            CliCommand = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer' -Name NoAutoplayfornonVolume -Value 1 -Type DWord",
            VerifyCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer' | Select NoAutoplayfornonVolume",
            Verification = "NoAutoplayfornonVolume = 1.",
            ValueMap = "1 = Enabled.",
            CliTokens = "NoAutoplayfornonVolume: blocks AutoPlay on non-volume (MTP/PTP) devices.",
            ConsoleTool = "gpedit.msc",
            DestinationLabel = "AutoPlay Policies → Disallow Autoplay for non-volume devices",
            GraphicalPathFull = "Computer Configuration > Administrative Templates > Windows Components > AutoPlay Policies > Disallow Autoplay for non-volume devices",
            ConsolePath = "Computer Configuration > Administrative Templates > Windows Components > AutoPlay Policies",
            YouAreHere = "gpedit.msc (root)",
            GoTo = "Computer Configuration > Administrative Templates > Windows Components > AutoPlay Policies > 'Disallow Autoplay for non-volume devices' > Enabled",
            GraphicalSteps = "1) AutoPlay Policies. 2) 'Disallow Autoplay for non-volume devices'. 3) Enabled.",
            UndoCli = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer' -Name NoAutoplayfornonVolume -Value 0",
            IgnoreConsequence = "MTP devices can trigger AutoPlay.",
            HasRegistryPath = true,
            RegistryPath = @"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\NoAutoplayfornonVolume",
            AlternativeToRegistry = "Prefer gpedit.msc → AutoPlay Policies."
        });

    // ── Item 16: Secure RDP (NLA) ──
    private static readonly bool _rdp = Register(
        new SubCheck
        {
            Id = "RDP-001.1",
            Title = "Require NLA for remote connections",
            Expected = "Enabled",
            WhatItDoes = "Forces authentication before a session is created.",
            Recommendation = "UserAuthentication = 1.",
            CheckCurrentCli = "Get-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp' | Select UserAuthentication",
            CliCommand = "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp' -Name UserAuthentication -Value 1",
            VerifyCli = "Get-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp' | Select UserAuthentication",
            Verification = "UserAuthentication = 1.",
            ValueMap = "1 = NLA required.",
            CliTokens = "UserAuthentication 1: require Network Level Authentication.",
            ConsoleTool = "gpedit.msc",
            DestinationLabel = "RD Session Host → Security → Require NLA",
            GraphicalPathFull = "Computer Configuration > Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Session Host > Security > Require user authentication for remote connections by using Network Level Authentication",
            ConsolePath = "… > Remote Desktop Session Host > Security",
            YouAreHere = "gpedit.msc (root)",
            GoTo = "Computer Configuration > Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Session Host > Security > 'Require user authentication for remote connections by using Network Level Authentication' > Enabled",
            GraphicalSteps = "1) gpedit.msc → Windows Components → Remote Desktop Services → RD Session Host → Security. 2) 'Require user authentication… NLA'. 3) Enabled.",
            UndoCli = "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp' -Name UserAuthentication -Value 0",
            IgnoreConsequence = "RDP brute-force surface remains.",
            HasRegistryPath = true,
            RegistryPath = @"HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\UserAuthentication",
            AlternativeToRegistry = "Prefer gpedit.msc → RD Session Host → Security."
        },
        new SubCheck
        {
            Id = "RDP-001.2",
            Title = "Encryption level + secure RPC",
            Expected = "High / Enabled",
            WhatItDoes = "Forces strong RDP encryption and authenticated RPC.",
            Recommendation = "MinEncryptionLevel=3, fEncryptRPCTraffic=1.",
            CheckCurrentCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' | Select MinEncryptionLevel,fEncryptRPCTraffic",
            CliCommand = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' -Name MinEncryptionLevel -Value 3; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' -Name fEncryptRPCTraffic -Value 1",
            VerifyCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' | Select MinEncryptionLevel,fEncryptRPCTraffic",
            Verification = "MinEncryptionLevel=3, fEncryptRPCTraffic=1.",
            ValueMap = "3 = High Level.",
            CliTokens = "MinEncryptionLevel 3: High; fEncryptRPCTraffic 1: secure RPC.",
            ConsoleTool = "gpedit.msc",
            DestinationLabel = "RD Session Host → Security → encryption + RPC",
            GraphicalPathFull = "Computer Configuration > Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Session Host > Security",
            ConsolePath = "… > Remote Desktop Session Host > Security",
            YouAreHere = "gpedit.msc (root)",
            GoTo = "Computer Configuration > Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Session Host > Security > 'Set client connection encryption level' > Enabled > High Level",
            GraphicalSteps = "1) Security node. 2) 'Set client connection encryption level' = High. 3) 'Require secure RPC communication' = Enabled.",
            UndoCli = "# revert values",
            IgnoreConsequence = "Weak encryption / MITM risk.",
            HasRegistryPath = true,
            RegistryPath = @"HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\MinEncryptionLevel",
            AlternativeToRegistry = "Prefer gpedit.msc → Security."
        },
        new SubCheck
        {
            Id = "RDP-001.3",
            Title = "Always prompt for password upon connection",
            Expected = "Enabled",
            WhatItDoes = "Forces password entry at each connection.",
            Recommendation = "fPromptForPassword = 1.",
            CheckCurrentCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' | Select fPromptForPassword",
            CliCommand = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' -Name fPromptForPassword -Value 1",
            VerifyCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' | Select fPromptForPassword",
            Verification = "fPromptForPassword = 1.",
            ValueMap = "1 = Enabled.",
            CliTokens = "fPromptForPassword 1: always ask for password.",
            ConsoleTool = "gpedit.msc",
            DestinationLabel = "RD Session Host → Security → prompt for password",
            GraphicalPathFull = "Computer Configuration > Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Session Host > Security > Always prompt for password upon connection",
            ConsolePath = "… > Remote Desktop Session Host > Security",
            YouAreHere = "gpedit.msc (root)",
            GoTo = "Computer Configuration > Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Session Host > Security > 'Always prompt for password upon connection' > Enabled",
            GraphicalSteps = "1) Security node. 2) 'Always prompt for password upon connection'. 3) Enabled.",
            UndoCli = "# set 0",
            IgnoreConsequence = "Saved credentials auto-used.",
            HasRegistryPath = true,
            RegistryPath = @"HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\fPromptForPassword",
            AlternativeToRegistry = "Prefer gpedit.msc → Security."
        },
        new SubCheck
        {
            Id = "RDP-001.4",
            Title = "Session limits + connection limit",
            Expected = "Idle 15m / Disconnected 1m / Connections 2",
            WhatItDoes = "Disconnects idle and ends disconnected sessions; caps concurrency.",
            Recommendation = "MaxIdleTime=900000, MaxDisconnectionTime=60000, MaxInstanceCount=2.",
            CheckCurrentCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' | Select MaxIdleTime,MaxDisconnectionTime,MaxInstanceCount",
            CliCommand = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' -Name MaxIdleTime -Value 900000; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' -Name MaxDisconnectionTime -Value 60000; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' -Name MaxInstanceCount -Value 2",
            VerifyCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' | Select MaxIdleTime,MaxDisconnectionTime",
            Verification = "MaxIdleTime=900000, MaxDisconnectionTime=60000, MaxInstanceCount=2.",
            ValueMap = "ms values.",
            CliTokens = "MaxIdleTime: idle disconnect (ms); MaxDisconnectionTime: disconnected session limit (ms).",
            ConsoleTool = "gpedit.msc",
            DestinationLabel = "RD Session Host → Session Time Limits / Connections",
            GraphicalPathFull = "Computer Configuration > Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Session Host > Session Time Limits (and Connections)",
            ConsolePath = "… > Remote Desktop Session Host > Session Time Limits",
            YouAreHere = "gpedit.msc (root)",
            GoTo = "Computer Configuration > Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Session Host > Session Time Limits > 'Set time limit for active but idle Remote Desktop Services sessions' > 15 minutes",
            GraphicalSteps = "1) Session Time Limits: set active-idle 15m, disconnected 1m. 2) Connections: limit number of connections = 2.",
            UndoCli = "# revert values",
            IgnoreConsequence = "Stale sessions linger.",
            HasRegistryPath = true,
            RegistryPath = @"HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\MaxIdleTime",
            AlternativeToRegistry = "Prefer gpedit.msc → Session Time Limits."
        });
}