namespace ISCM.Domain.Entities;

// Step 28 fix: all GPO/console paths verified 1:1 against
// "Windows11_Hardening_17_Items_Guide_Revised.pdf".
// Covers PDF items 1 (Password), 8-subsets (UAC / LM / ADM).
public static partial class GuidanceCatalog
{
    // ── Item 1: Password Policy (secpol.msc → Account Policies → Password Policy) ──
    private static readonly bool _pwd = Register(
        new SubCheck
        {
            Id = "PWD-001.1",
            Title = "Enforce password history",
            Expected = "24 passwords remembered",
            WhatItDoes = "Prevents users from reusing recent passwords.",
            Recommendation = "Keep history at 24.",
            CheckCurrentCli = "net accounts",
            CliCommand = "# secpol.msc → Account Policies → Password Policy → Enforce password history = 24",
            VerifyCli = "net accounts",
            Verification = "secpol → Password Policy → 'Enforce password history' shows 24.",
            ValueMap = "",
            CliTokens = "",
            ConsoleTool = "secpol.msc",
            DestinationLabel = "Password Policy → Enforce password history",
            GraphicalPathFull = "Computer Configuration > Windows Settings > Security Settings > Account Policies > Password Policy > Enforce password history",
            ConsolePath = "Computer Configuration > Windows Settings > Security Settings > Account Policies > Password Policy",
            YouAreHere = "secpol.msc → Security Settings → Account Policies",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Account Policies > Password Policy > 'Enforce password history' > 24",
            GraphicalSteps = "1) Open secpol.msc. 2) Expand Account Policies. 3) Click Password Policy. 4) Right pane: double-click 'Enforce password history'. 5) Set 24.",
            UndoCli = "# set back to previous value",
            IgnoreConsequence = "Weak reuse of old passwords becomes possible.",
            HasRegistryPath = false
        },
        new SubCheck
        {
            Id = "PWD-001.2",
            Title = "Maximum password age",
            Expected = "60 days",
            WhatItDoes = "Forces periodic password changes.",
            Recommendation = "Set 60 days.",
            CheckCurrentCli = "net accounts",
            CliCommand = "# secpol.msc → Password Policy → Maximum password age = 60",
            VerifyCli = "net accounts",
            Verification = "'Maximum password age' shows 60.",
            ConsoleTool = "secpol.msc",
            DestinationLabel = "Password Policy → Maximum password age",
            GraphicalPathFull = "Computer Configuration > Windows Settings > Security Settings > Account Policies > Password Policy > Maximum password age",
            ConsolePath = "Computer Configuration > Windows Settings > Security Settings > Account Policies > Password Policy",
            YouAreHere = "secpol.msc → Security Settings → Account Policies",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Account Policies > Password Policy > 'Maximum password age' > 60",
            GraphicalSteps = "1) secpol.msc → Account Policies → Password Policy. 2) Double-click 'Maximum password age'. 3) Set 60.",
            UndoCli = "# revert",
            IgnoreConsequence = "Stale passwords remain valid indefinitely.",
            HasRegistryPath = false
        },
        new SubCheck
        {
            Id = "PWD-001.3",
            Title = "Minimum password age",
            Expected = "1 day",
            WhatItDoes = "Stops rapid password cycling to bypass history.",
            Recommendation = "Set 1 day.",
            CheckCurrentCli = "net accounts",
            CliCommand = "# secpol.msc → Password Policy → Minimum password age = 1",
            VerifyCli = "net accounts",
            Verification = "'Minimum password age' shows 1.",
            ConsoleTool = "secpol.msc",
            DestinationLabel = "Password Policy → Minimum password age",
            GraphicalPathFull = "Computer Configuration > Windows Settings > Security Settings > Account Policies > Password Policy > Minimum password age",
            ConsolePath = "Computer Configuration > Windows Settings > Security Settings > Account Policies > Password Policy",
            YouAreHere = "secpol.msc → Security Settings → Account Policies",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Account Policies > Password Policy > 'Minimum password age' > 1",
            GraphicalSteps = "1) secpol.msc → Account Policies → Password Policy. 2) Double-click 'Minimum password age'. 3) Set 1.",
            UndoCli = "# revert",
            IgnoreConsequence = "Users can cycle passwords instantly to defeat history.",
            HasRegistryPath = false
        },
        new SubCheck
        {
            Id = "PWD-001.4",
            Title = "Minimum password length",
            Expected = "14 characters",
            WhatItDoes = "Raises resistance to brute-force.",
            Recommendation = "Enforce 14.",
            CheckCurrentCli = "net accounts",
            CliCommand = "net accounts /minpwlen:14",
            VerifyCli = "net accounts",
            Verification = "'Minimum password length' shows 14.",
            ConsoleTool = "secpol.msc",
            DestinationLabel = "Password Policy → Minimum password length",
            GraphicalPathFull = "Computer Configuration > Windows Settings > Security Settings > Account Policies > Password Policy > Minimum password length",
            ConsolePath = "Computer Configuration > Windows Settings > Security Settings > Account Policies > Password Policy",
            YouAreHere = "secpol.msc → Security Settings → Account Policies",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Account Policies > Password Policy > 'Minimum password length' > 14",
            GraphicalSteps = "1) secpol.msc → Account Policies → Password Policy. 2) Double-click 'Minimum password length'. 3) Set 14.",
            UndoCli = "net accounts /minpwlen:0",
            IgnoreConsequence = "Short passwords stay brute-forceable.",
            HasRegistryPath = false
        },
        new SubCheck
        {
            Id = "PWD-001.5",
            Title = "Password must meet complexity requirements",
            Expected = "Enabled",
            WhatItDoes = "Requires mixed character classes.",
            Recommendation = "Enabled.",
            CheckCurrentCli = "# secpol.msc",
            CliCommand = "# secpol.msc → Password Policy → Complexity = Enabled",
            VerifyCli = "# secpol.msc",
            Verification = "'Password must meet complexity requirements' shows Enabled.",
            ConsoleTool = "secpol.msc",
            DestinationLabel = "Password Policy → Complexity requirements",
            GraphicalPathFull = "Computer Configuration > Windows Settings > Security Settings > Account Policies > Password Policy > Password must meet complexity requirements",
            ConsolePath = "Computer Configuration > Windows Settings > Security Settings > Account Policies > Password Policy",
            YouAreHere = "secpol.msc → Security Settings → Account Policies",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Account Policies > Password Policy > 'Password must meet complexity requirements' > Enabled",
            GraphicalSteps = "1) secpol.msc → Account Policies → Password Policy. 2) Double-click complexity setting. 3) Enable.",
            UndoCli = "# revert",
            IgnoreConsequence = "Simple passwords allowed.",
            HasRegistryPath = false
        },
        new SubCheck
        {
            Id = "PWD-001.6",
            Title = "Store passwords using reversible encryption",
            Expected = "Disabled",
            WhatItDoes = "Prevents weak recoverable storage.",
            Recommendation = "Disabled.",
            CheckCurrentCli = "# secpol.msc",
            CliCommand = "# secpol.msc → Password Policy → Reversible encryption = Disabled",
            VerifyCli = "# secpol.msc",
            Verification = "'Store passwords using reversible encryption' shows Disabled.",
            ConsoleTool = "secpol.msc",
            DestinationLabel = "Password Policy → Reversible encryption",
            GraphicalPathFull = "Computer Configuration > Windows Settings > Security Settings > Account Policies > Password Policy > Store passwords using reversible encryption",
            ConsolePath = "Computer Configuration > Windows Settings > Security Settings > Account Policies > Password Policy",
            YouAreHere = "secpol.msc → Security Settings → Account Policies",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Account Policies > Password Policy > 'Store passwords using reversible encryption' > Disabled",
            GraphicalSteps = "1) secpol.msc → Account Policies → Password Policy. 2) Double-click reversible encryption. 3) Disable.",
            UndoCli = "# revert",
            IgnoreConsequence = "Passwords stored in a recoverable form.",
            HasRegistryPath = false
        });

    // ── Item 8 subset: UAC (secpol.msc → Local Policies → Security Options) ──
    private static readonly bool _uac = Register(
        new SubCheck
        {
            Id = "UAC-001.1",
            Title = "User Account Control: Run all administrators in Admin Approval Mode",
            Expected = "Enabled",
            WhatItDoes = "Forces elevation through UAC instead of silent admin execution.",
            Recommendation = "EnableLUA = 1.",
            CheckCurrentCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' | Select EnableLUA",
            CliCommand = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name EnableLUA -Value 1 -Type DWord",
            VerifyCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' | Select EnableLUA",
            Verification = "EnableLUA = 1. Restart required.",
            ValueMap = "1 = Enabled, 0 = Disabled",
            CliTokens = "-Name EnableLUA: the UAC master switch; -Value 1: turn on Admin Approval Mode.",
            ConsoleTool = "secpol.msc",
            DestinationLabel = "Security Options → Run all administrators in Admin Approval Mode",
            GraphicalPathFull = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options > User Account Control: Run all administrators in Admin Approval Mode",
            ConsolePath = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options",
            YouAreHere = "secpol.msc → Security Settings → Local Policies",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options > 'User Account Control: Run all administrators in Admin Approval Mode' > Enabled",
            GraphicalSteps = "1) secpol.msc. 2) Expand Local Policies. 3) Click Security Options. 4) Right pane: double-click 'User Account Control: Run all administrators in Admin Approval Mode'. 5) Enabled.",
            UndoCli = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name EnableLUA -Value 0",
            IgnoreConsequence = "Admins run fully elevated; silent privilege abuse possible.",
            HasRegistryPath = true,
            RegistryPath = @"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\EnableLUA",
            AlternativeToRegistry = "Prefer secpol.msc → Security Options over manual registry editing."
        },
        new SubCheck
        {
            Id = "UAC-001.2",
            Title = "User Account Control: Behavior of the elevation prompt for administrators",
            Expected = "Prompt for consent on the secure desktop",
            WhatItDoes = "Moves elevation prompts to the secure desktop.",
            Recommendation = "ConsentPromptBehaviorAdmin = 2.",
            CheckCurrentCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' | Select ConsentPromptBehaviorAdmin",
            CliCommand = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name ConsentPromptBehaviorAdmin -Value 2 -Type DWord",
            VerifyCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' | Select ConsentPromptBehaviorAdmin",
            Verification = "ConsentPromptBehaviorAdmin = 2.",
            ValueMap = "2 = Prompt for consent on secure desktop, 0 = Elevate without prompting.",
            CliTokens = "-Name ConsentPromptBehaviorAdmin: admin elevation prompt behavior; -Value 2: secure-desktop consent.",
            ConsoleTool = "secpol.msc",
            DestinationLabel = "Security Options → Elevation prompt behavior",
            GraphicalPathFull = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options > User Account Control: Behavior of the elevation prompt for administrators",
            ConsolePath = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options",
            YouAreHere = "secpol.msc → Security Settings → Local Policies",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options > 'User Account Control: Behavior of the elevation prompt for administrators' > Prompt for consent on the secure desktop",
            GraphicalSteps = "1) secpol.msc → Local Policies → Security Options. 2) Double-click 'User Account Control: Behavior of the elevation prompt for administrators'. 3) Choose 'Prompt for consent on the secure desktop'.",
            UndoCli = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name ConsentPromptBehaviorAdmin -Value 0",
            IgnoreConsequence = "Elevation may occur without a secure prompt.",
            HasRegistryPath = true,
            RegistryPath = @"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\ConsentPromptBehaviorAdmin",
            AlternativeToRegistry = "Prefer secpol.msc → Security Options."
        },
        new SubCheck
        {
            Id = "UAC-001.3",
            Title = "User Account Control: Detect application installations and prompt for elevation",
            Expected = "Enabled",
            WhatItDoes = "Detects installer behavior that requires elevation.",
            Recommendation = "EnableInstallerDetection = 1.",
            CheckCurrentCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' | Select EnableInstallerDetection",
            CliCommand = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name EnableInstallerDetection -Value 1 -Type DWord",
            VerifyCli = "Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' | Select EnableInstallerDetection",
            Verification = "EnableInstallerDetection = 1.",
            ValueMap = "1 = Enabled, 0 = Disabled.",
            CliTokens = "-Name EnableInstallerDetection: catches installers needing admin rights.",
            ConsoleTool = "secpol.msc",
            DestinationLabel = "Security Options → Detect application installations",
            GraphicalPathFull = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options > User Account Control: Detect application installations and prompt for elevation",
            ConsolePath = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options",
            YouAreHere = "secpol.msc → Security Settings → Local Policies",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options > 'User Account Control: Detect application installations and prompt for elevation' > Enabled",
            GraphicalSteps = "1) secpol.msc → Local Policies → Security Options. 2) Double-click 'User Account Control: Detect application installations and prompt for elevation'. 3) Enabled.",
            UndoCli = "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name EnableInstallerDetection -Value 0",
            IgnoreConsequence = "Silent installer elevation goes unnoticed.",
            HasRegistryPath = true,
            RegistryPath = @"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\EnableInstallerDetection",
            AlternativeToRegistry = "Prefer secpol.msc → Security Options."
        });

    // ── Item 8 subset: LM / NTLM ──
    private static readonly bool _lm = Register(
        new SubCheck
        {
            Id = "LM-001.1",
            Title = "Network security: LAN Manager authentication level",
            Expected = "Send NTLMv2 response only. Refuse LM & NTLM",
            WhatItDoes = "Forces the strongest NTLM variant and blocks weak ones.",
            Recommendation = "LmCompatibilityLevel = 5.",
            CheckCurrentCli = "Get-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' | Select LmCompatibilityLevel",
            CliCommand = "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name LmCompatibilityLevel -Value 5 -Type DWord",
            VerifyCli = "Get-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' | Select LmCompatibilityLevel",
            Verification = "LmCompatibilityLevel = 5.",
            ValueMap = "5 = NTLMv2 only, 0 = Send LM & NTLM.",
            CliTokens = "-Name LmCompatibilityLevel: NTLM negotiation level; -Value 5: refuse LM & NTLM.",
            ConsoleTool = "secpol.msc",
            DestinationLabel = "Security Options → LAN Manager authentication level",
            GraphicalPathFull = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options > Network security: LAN Manager authentication level",
            ConsolePath = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options",
            YouAreHere = "secpol.msc → Security Settings → Local Policies",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options > 'Network security: LAN Manager authentication level' > Send NTLMv2 response only. Refuse LM & NTLM",
            GraphicalSteps = "1) secpol.msc → Local Policies → Security Options. 2) Double-click 'Network security: LAN Manager authentication level'. 3) Pick 'Send NTLMv2 response only. Refuse LM & NTLM'.",
            UndoCli = "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name LmCompatibilityLevel -Value 0",
            IgnoreConsequence = "Weak LM/NTLM hashes remain usable by attackers.",
            HasRegistryPath = true,
            RegistryPath = @"HKLM\SYSTEM\CurrentControlSet\Control\Lsa\LmCompatibilityLevel",
            AlternativeToRegistry = "Prefer secpol.msc → Security Options."
        },
        new SubCheck
        {
            Id = "LM-001.2",
            Title = "Network security: Do not store LAN Manager hash value on next password change",
            Expected = "Enabled",
            WhatItDoes = "Stops Windows from storing the weak LM hash.",
            Recommendation = "NoLMHash = 1.",
            CheckCurrentCli = "Get-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' | Select NoLMHash",
            CliCommand = "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name NoLMHash -Value 1 -Type DWord",
            VerifyCli = "Get-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' | Select NoLMHash",
            Verification = "NoLMHash = 1.",
            ValueMap = "1 = Do not store LM hash, 0 = Store LM hash.",
            CliTokens = "-Name NoLMHash: disables LM hash storage on next password change.",
            ConsoleTool = "secpol.msc",
            DestinationLabel = "Security Options → Do not store LM hash",
            GraphicalPathFull = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options > Network security: Do not store LAN Manager hash value on next password change",
            ConsolePath = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options",
            YouAreHere = "secpol.msc → Security Settings → Local Policies",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options > 'Network security: Do not store LAN Manager hash value on next password change' > Enabled",
            GraphicalSteps = "1) secpol.msc → Local Policies → Security Options. 2) Double-click 'Network security: Do not store LAN Manager hash value on next password change'. 3) Enabled.",
            UndoCli = "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name NoLMHash -Value 0",
            IgnoreConsequence = "Weak LM hash stored and crackable.",
            HasRegistryPath = true,
            RegistryPath = @"HKLM\SYSTEM\CurrentControlSet\Control\Lsa\NoLMHash",
            AlternativeToRegistry = "Prefer secpol.msc → Security Options."
        });

    // ── Item 8 subset: Administrator / blank passwords ──
    private static readonly bool _adm = Register(
        new SubCheck
        {
            Id = "ADM-001.1",
            Title = "Accounts: Administrator account status",
            Expected = "Disabled",
            WhatItDoes = "Disables the built-in Administrator account.",
            Recommendation = "net user Administrator /active:no.",
            CheckCurrentCli = "net user Administrator",
            CliCommand = "net user Administrator /active:no",
            VerifyCli = "net user Administrator",
            Verification = "'Account active' shows No.",
            ValueMap = "/active:no = Disabled, /active:yes = Enabled.",
            CliTokens = "Administrator: built-in account name; /active:no: disables the account.",
            ConsoleTool = "secpol.msc",
            DestinationLabel = "Security Options → Administrator account status",
            GraphicalPathFull = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options > Accounts: Administrator account status",
            ConsolePath = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options",
            YouAreHere = "secpol.msc → Security Settings → Local Policies",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options > 'Accounts: Administrator account status' > Disabled",
            GraphicalSteps = "1) secpol.msc → Local Policies → Security Options. 2) Right pane: double-click 'Accounts: Administrator account status'. 3) Disabled.",
            UndoCli = "net user Administrator /active:yes",
            IgnoreConsequence = "Built-in admin stays active and targetable.",
            HasRegistryPath = false
        },
        new SubCheck
        {
            Id = "ADM-001.2",
            Title = "Accounts: Rename administrator account",
            Expected = "Set to a unique non-obvious name",
            WhatItDoes = "Hides the well-known 'Administrator' name from attackers.",
            Recommendation = "Rename the SID -500 account.",
            CheckCurrentCli = "Get-LocalUser | Where-Object { $_.SID.Value -like '*-500' } | Select Name",
            CliCommand = "$a = Get-LocalUser | Where-Object { $_.SID.Value -like '*-500' }; Rename-LocalUser -SID $a.SID -NewName 'SysOps-X1'",
            VerifyCli = "Get-LocalUser | Where-Object { $_.SID.Value -like '*-500' } | Select Name",
            Verification = "Name is not 'Administrator'.",
            ValueMap = "",
            CliTokens = "SID -500: the built-in administrator; Rename-LocalUser: changes its display name.",
            ConsoleTool = "secpol.msc",
            DestinationLabel = "Security Options → Rename administrator account",
            GraphicalPathFull = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options > Accounts: Rename administrator account",
            ConsolePath = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options",
            YouAreHere = "secpol.msc → Security Settings → Local Policies",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options > 'Accounts: Rename administrator account' > Set to a unique non-obvious name",
            GraphicalSteps = "1) secpol.msc. 2) Expand Local Policies. 3) Click Security Options. 4) Right pane: double-click 'Accounts: Rename administrator account'. 5) Enter a unique non-obvious name.",
            UndoCli = "# rename back if required",
            IgnoreConsequence = "Default admin name stays exposed.",
            HasRegistryPath = false
        },
        new SubCheck
        {
            Id = "ADM-001.3",
            Title = "Accounts: Limit local account use of blank passwords to console logon only",
            Expected = "Enabled",
            WhatItDoes = "Stops blank-password local accounts from being used over the network.",
            Recommendation = "LimitBlankPasswordUse = 1.",
            CheckCurrentCli = "Get-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' | Select LimitBlankPasswordUse",
            CliCommand = "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name LimitBlankPasswordUse -Value 1 -Type DWord",
            VerifyCli = "Get-ItemProperty 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' | Select LimitBlankPasswordUse",
            Verification = "LimitBlankPasswordUse = 1.",
            ValueMap = "1 = Enabled, 0 = Disabled.",
            CliTokens = "-Name LimitBlankPasswordUse: restricts blank-password accounts to console only.",
            ConsoleTool = "secpol.msc",
            DestinationLabel = "Security Options → Limit blank password use",
            GraphicalPathFull = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options > Accounts: Limit local account use of blank passwords to console logon only",
            ConsolePath = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options",
            YouAreHere = "secpol.msc → Security Settings → Local Policies",
            GoTo = "Computer Configuration > Windows Settings > Security Settings > Local Policies > Security Options > 'Accounts: Limit local account use of blank passwords to console logon only' > Enabled",
            GraphicalSteps = "1) secpol.msc → Local Policies → Security Options. 2) Double-click 'Accounts: Limit local account use of blank passwords to console logon only'. 3) Enabled.",
            UndoCli = "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name LimitBlankPasswordUse -Value 0",
            IgnoreConsequence = "Blank-password accounts usable over the network.",
            HasRegistryPath = true,
            RegistryPath = @"HKLM\SYSTEM\CurrentControlSet\Control\Lsa\LimitBlankPasswordUse",
            AlternativeToRegistry = "Prefer secpol.msc → Security Options."
        });
}